print("Feladat 0015")
print("        __")
print("      _ ||")
print("     / \||")
print("    /   \|")
print("   /     \ ")
print("   |     |")
print("   |     |")
print("   -------\n")
print("Feladat 0025")
print("          ___|___")
print("            / \                                __|__")
print("---0---0---(___)---0---0---             --o--o--(_)--o--o--")
